### ISSUE TITLE
Feature: JEI Compatibility (In-World Recipes)

### ISSUE THREAD

**Issue by bconlon1** [Gilded-Games/The-Aether#852]
JEI support for in-world recipes such as block banning.

May be more complex due to needing to display certain values like blockstates, biome tags if relevant, and may also require some additional GUI art or at least a GUI design mockup to plan the layout.

**Comment by saintselect** [comment]
WIP prototype of how this could look. I'll open a PR once I've fixed some of the glaring issues (liquid rendering, weird lighting, biome tags could be displayed more neatly).
![image](https://user-images.githubusercontent.com/82977035/204891620-ad4436d0-8597-4dbf-9ec2-9528f0c4e831.png)
![image](https://user-images.githubusercontent.com/82977035/204891877-f50bab55-4f76-4467-ac4c-4d7b2a60f6d3.png)
![image](https://user-images.githubusercontent.com/82977035/204891699-c1f0b82d-217f-4add-a812-334b54560c81.png)

**Comment by bconlon1** [comment]
@saintselect 
Looks good to me! Although maybe there should be something to display blockstate values for blocks as well? It could make things more clear for certain conversions like with candles.

**Comment by bconlon1** [comment]
Issue no longer blocked; JEI has released for 1.19.3.

**Comment by bconlon1** [comment]
We're still missing JEI support for `icestone_freezable`, `accessory_freezable`, `placement_conversion`,`item_placement_ban`, and `block_placement_ban`.

**Comment by Burning-Cactus** [comment]
Whoops, I forgot about those ones
